---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/b2m_trans_conf/b2m_trans_conf.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/85085/articles/289927/master/folder/figures/b2m_trans_conf"
    url: "/users/85085/articles/289927/master/file/figures/b2m_trans_conf/b2m_trans_conf.png"
