---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/rdf_CA501_water_CIS/rdf_CA501_water_CIS.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/85085/articles/289927/master/file/figures/rdf_CA501_water_CIS/rdf_CA501_water_CIS.png"
