---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mapcolor_fes_psi_phi/mapcolor_fes_psi_phi.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/85085/articles/289927/master/file/figures/mapcolor_fes_psi_phi/mapcolor_fes_psi_phi.png"
    folder_url: "/users/85085/articles/289927/master/folder/figures/mapcolor_fes_psi_phi"
